title: Carolin Müller
description: Dr. rer. nat. in Physical Chemistry
show_downloads: true

baseurl: ""
url: "https://carolin-m.github.io" 

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
author: Carolin Müller
image: /images/caro.png

github_username: carolin-m
orcid_id: 0000-0002-5968-2216

researchgate:
  username: Carolin-Mueller-6
plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now','about','publications','teaching', 'contact']
